# Generated by Django 3.1 on 2020-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200902_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sl',
            name='wykonanie_okres',
            field=models.PositiveIntegerField(verbose_name='Wykonianie w danym okresie [szt]'),
        ),
    ]
