# Generated by Django 3.1 on 2020-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200902_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mb',
            name='dlugosc',
            field=models.PositiveIntegerField(verbose_name='Długość przejścia [mb]'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='start_kilometraz',
            field=models.PositiveIntegerField(verbose_name='Start metody Kilometraż [format: 32 005 m]'),
        ),
        migrations.AlterField(
            model_name='ob',
            name='ilosc',
            field=models.PositiveIntegerField(verbose_name='Ilość Calostyków [szt]'),
        ),
        migrations.AlterField(
            model_name='ob',
            name='wykonanie_all',
            field=models.PositiveIntegerField(verbose_name='Wykonianie narastająco [szt]'),
        ),
        migrations.AlterField(
            model_name='ob',
            name='wykonanie_okres',
            field=models.PositiveIntegerField(verbose_name='Wykonianie w danym okresie [szt]'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='dlugosc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Długość gazociągu [mb]'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='odcinki',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ilość odcinków próbnych'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='psp',
            field=models.PositiveIntegerField(verbose_name='Numer ewidencyjny PSP'),
        ),
        migrations.AlterField(
            model_name='sl',
            name='ilosc',
            field=models.PositiveIntegerField(verbose_name='Ilość spoin [szt]'),
        ),
        migrations.AlterField(
            model_name='sl',
            name='wykonanie_all',
            field=models.PositiveIntegerField(verbose_name='Wykonianie narastająco [szt]'),
        ),
        migrations.AlterField(
            model_name='sm',
            name='ilosc',
            field=models.PositiveIntegerField(verbose_name='Ilość spoin [szt]'),
        ),
        migrations.AlterField(
            model_name='sm',
            name='wykonanie_all',
            field=models.PositiveIntegerField(verbose_name='Wykonianie narastająco [szt]'),
        ),
        migrations.AlterField(
            model_name='sm',
            name='wykonanie_okres',
            field=models.PositiveIntegerField(verbose_name='Wykonianie w danym okresie [szt]'),
        ),
        migrations.AlterField(
            model_name='uk',
            name='ilosc',
            field=models.PositiveIntegerField(verbose_name='Ilość układki [mb]'),
        ),
        migrations.AlterField(
            model_name='uk',
            name='wykonanie_all',
            field=models.PositiveIntegerField(verbose_name='Wykonianie narastająco [mb]'),
        ),
        migrations.AlterField(
            model_name='uk',
            name='wykonanie_okres',
            field=models.PositiveIntegerField(verbose_name='Wykonianie w danym okresie [mb]'),
        ),
    ]
